import streamlit as st
import os
from src.application_to_one_text.prediction import predict_text_class


# Function to retrieve available models based on feature type
def get_available_models(feature_type):
    models_dir = "outputs/models/"
    available_models = []
    if os.path.exists(models_dir):
        for filename in os.listdir(models_dir):
            if filename.endswith("_model.joblib") and feature_type in filename:
                model_name = filename.replace("_model.joblib", "")
                available_models.append(model_name)
    return available_models

# -------------------------------
# Title
# -------------------------------


st.title("AI-Generated Text Detection 🤖 vs Human-Written ✍️")

st.markdown("""
This application predicts whether a text was written by a human
or generated by a language model (LLM).
""")

# -------------------------------
# Sidebar: model selection
# -------------------------------

st.sidebar.header("Configuration")

# Select feature type
feature_type = st.sidebar.selectbox(
    "Which type of features would you like to use?",
    ("bert", "roberta", "sbert", "handcrafted")
)

# Dynamically fetch available models based on feature_type
available_models = get_available_models(feature_type)

# If no models are found
if not available_models:
    st.sidebar.warning(f"No models found for '{feature_type}'.")
    model_name = None
else:
    model_name = st.sidebar.selectbox(
        "Which trained model would you like to use?",
        available_models
    )

# -------------------------------
# Text input area
# -------------------------------


st.subheader("Enter your text 👇")

user_text = st.text_area(
    "Text to analyze",
    placeholder="Write or paste your text here...",
    height=300
)

# Prediction button
if st.button("Run prediction 🚀"):
    if user_text.strip() == "":
        st.warning("Please enter a text before making a prediction.")
    elif model_name is None:
        st.error("No model available. Please select another feature type.")
    else:
        with st.spinner("Analyzing the text..."):
            prediction = predict_text_class(user_text, model_name, feature_type)

            # Display the result
            if prediction == 0:
                st.success("✅ This text is most likely **human-written**.")
            else:
                st.error("🚨 This text is most likely **generated by an LLM**.")
